# Generated by Django 4.2.23 on 2025-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.CharField(help_text='e.g. 1 hour, 2-3 days turnaround', max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
