# Generated by Django 4.2.23 on 2025-07-01 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photoshoot_type', models.CharField(choices=[('Animals', 'Pets & Wildlife'), ('Children', 'Children'), ('Commercial', 'Commercial'), ('Events', 'Events'), ('Family', 'Family'), ('Headshots', 'Headshots & Products'), ('Landscapes', 'Landscape & Property'), ('Vehicle', 'Vehicle'), ('Wedding', 'Weddings & Ceremonies')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
